const kana = [
	{ romaji: 'a', symbol: 'あ | ア' },
	{ romaji: 'i', symbol: 'い | イ' },
	{ romaji: 'u', symbol: 'う | ウ' },
	{ romaji: 'e', symbol: 'え | エ' },
	{ romaji: 'o', symbol: 'お | オ' },
	{ romaji: 'ka', symbol: 'か | カ' },
	{ romaji: 'ki', symbol: 'き | キ' },
	{ romaji: 'ku', symbol: 'く | ク' },
	{ romaji: 'ke', symbol: 'け | ケ' },
	{ romaji: 'ko', symbol: 'こ | コ' },
	{ romaji: 'sa', symbol: 'さ | サ' },
	{ romaji: 'shi', symbol: 'し | シ' },
	{ romaji: 'se', symbol: 'せ | セ' },
	{ romaji: 'su', symbol: 'す | ス' },
	{ romaji: 'so', symbol: 'そ | ソ' },
	{ romaji: 'ta', symbol: 'た | タ' },
	{ romaji: 'no', symbol: 'の | ノ' },
	{ romaji: 'tsu', symbol: 'つ | ツ' },
	{ romaji: 'chi', symbol: 'ち | チ' },
	{ romaji: 'te', symbol: 'て | テ' },
	{ romaji: 'to', symbol: 'と | ト' },
	{ romaji: 'na', symbol: 'な | ナ' },
	{ romaji: 'ne', symbol: 'ね | ネ' },
	{ romaji: 'ni', symbol: 'に | ニ' },
	{ romaji: 'nu', symbol: 'ぬ | ヌ' },
	{ romaji: 'ha', symbol: 'は | ハ' },
	{ romaji: 'hi', symbol: 'ひ | ヒ' },
	{ romaji: 'ho', symbol: 'ほ | ホ' },
	{ romaji: 'ma', symbol: 'ま | マ' },
	{ romaji: 'mi', symbol: 'み | ミ' },
	{ romaji: 'mo', symbol: 'も | モ' },
	{ romaji: 'yu', symbol: 'ゆ | ユ' },
	{ romaji: 'ra', symbol: 'ら | ラ' },
	{ romaji: 'ri', symbol: 'り | リ' },
	{ romaji: 'ru', symbol: 'る | ル' },
	{ romaji: 'wa', symbol: 'わ | ワ' },
	{ romaji: 'n', symbol: 'ん  | ン' },
	{ romaji: 'fu', symbol: 'ふ | フ' },
	{ romaji: 'ga', symbol: 'が | ガ' },
	{ romaji: 'gi', symbol: 'ぎ | ギ' },
	{ romaji: 'gu', symbol: 'ぐ | グ' },
	{ romaji: 'go', symbol: 'ご | ゴ' },
	{ romaji: 'da', symbol: 'だ | ダ' },
	{ romaji: 'de', symbol: 'で | デ' },
	{ romaji: 'do', symbol: 'ど | ド' },
	{ romaji: 'he', symbol: 'へ | へ' },
	{ romaji: 'mu', symbol: 'む | ム' },
	{ romaji: 'me', symbol: 'め | メ' },
	{ romaji: 'ya', symbol: 'や | ヤ' },
	{ romaji: 'yo', symbol: 'よ | ヨ' },
	{ romaji: 're', symbol: 'れ | レ' },
	{ romaji: 'ro', symbol: 'ろ | ロ' },
	{ romaji: 'wo', symbol: 'を | ヲ' },
	{ romaji: 'pa', symbol: 'ぱ | パ' },
	{ romaji: 'pi', symbol: 'ぴ | ピ' },
	{ romaji: 'pu', symbol: 'ぷ | プ' },
	{ romaji: 'pe', symbol: 'ぺ | ペ' },
	{ romaji: 'po', symbol: 'ぽ | ポ' },
	{ romaji: 'ge', symbol: 'げ | ゲ' },
	{ romaji: 'ba', symbol: 'ば | バ' },
	{ romaji: 'bi', symbol: 'び | ビ' },
	{ romaji: 'bu', symbol: 'ぶ | ブ' },
	{ romaji: 'be', symbol: 'べ | べ' },
	{ romaji: 'bo', symbol: 'ぼ | ボ' },
	{ romaji: 'za', symbol: 'ざ | ザ' },
	{ romaji: 'zi', symbol: 'じ | ジ' },
	{ romaji: 'zu', symbol: 'ず | ズ' },
	{ romaji: 'ze', symbol: 'ぜ | ゼ' },
	{ romaji: 'zo', symbol: 'ぞ | ゾ' },
	{ romaji: 'di', symbol: 'ぢ | ヂ' },
	{ romaji: 'du', symbol: 'づ | ヅ' },
]

const index = Math.floor(Math.random() * kana.length)

document.querySelector('#kana').innerHTML = kana[index].symbol
document.querySelector('#romaji').innerHTML = kana[index].romaji

const intervalo = 10 * 60 * 1000

setInterval(() => location.reload(), intervalo)